RECEIPT_TRANSLATIONS = {
    'en': {
        'title': 'Order Receipt',
        'order_number': 'Order #',
        'date': 'Date',
        'customer': 'Customer',
        'order_items': 'Order Items',
        'product': 'Product',
        'quantity': 'Qty',
        'unit_price': 'Unit Price',
        'total': 'Total',
        'subtotal': 'Subtotal',
        'discount': 'Discount',
        'payment_method': 'Payment Method',
        'payment_status': 'Payment Status',
        'thank_you': 'Thank you for your purchase!',
        'receipt_generated': 'Receipt generated on'
    },
    'es': {
        'title': 'Recibo de Orden',
        'order_number': 'Orden #',
        'date': 'Fecha',
        'customer': 'Cliente',
        'order_items': 'Artículos de la Orden',
        'product': 'Producto',
        'quantity': 'Cant',
        'unit_price': 'Precio Unitario',
        'total': 'Total',
        'subtotal': 'Subtotal',
        'discount': 'Descuento',
        'payment_method': 'Método de Pago',
        'payment_status': 'Estado de Pago',
        'thank_you': '¡Gracias por su compra!',
        'receipt_generated': 'Recibo generado el'
    }
}

REPORT_TRANSLATIONS = {
    'en': {
        'sales_by_customer': 'Sales by Customer',
        'best_sellers': 'Best Sellers',
        'sales_by_period': 'Sales by Period',
        'product_performance': 'Product Performance',
        'inventory_status': 'Inventory Status',
        'order_receipt': 'Order Receipt',
        'customer_orders': 'Customer Orders',
        'generated_on': 'Generated on',
        'period': 'Period',
        'customer': 'Customer',
        'product': 'Product',
        'date': 'Date',
        'total': 'Total',
        'quantity': 'Quantity',
        'price': 'Price',
        'status': 'Status',
        'category': 'Category',
        'revenue': 'Revenue',
        'order_count': 'Order Count',
        'average_order': 'Average Order',
        'stock': 'Stock'
    },
    'es': {
        'sales_by_customer': 'Ventas por Cliente',
        'best_sellers': 'Más Vendidos',
        'sales_by_period': 'Ventas por Periodo',
        'product_performance': 'Rendimiento de Productos',
        'inventory_status': 'Estado de Inventario',
        'order_receipt': 'Recibo de Orden',
        'customer_orders': 'Órdenes del Cliente',
        'generated_on': 'Generado el',
        'period': 'Periodo',
        'customer': 'Cliente',
        'product': 'Producto',
        'date': 'Fecha',
        'total': 'Total',
        'quantity': 'Cantidad',
        'price': 'Precio',
        'status': 'Estado',
        'category': 'Categoría',
        'revenue': 'Ingresos',
        'order_count': 'Cantidad de Órdenes',
        'average_order': 'Promedio por Orden',
        'stock': 'Existencias'
    }
}