# Generated by Django 5.2 on 2025-05-26 15:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_user_phone'),
        ('orders', '0006_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('customer', 'Customer'), ('delivery', 'Delivery')], default='customer', max_length=10),
        ),
        migrations.CreateModel(
            name='DeliveryAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('assigned', 'Asignado'), ('in_progress', 'En progreso'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], default='assigned', max_length=20)),
                ('assignment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('delivery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='orders.delivery')),
                ('delivery_person', models.ForeignKey(limit_choices_to={'role': 'delivery'}, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeliveryProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identification_number', models.CharField(max_length=30, unique=True)),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('busy', 'Ocupado'), ('offline', 'Fuera de línea')], default='available', max_length=20)),
                ('vehicle_type', models.CharField(blank=True, max_length=50, null=True)),
                ('license_plate', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
