# Generated by Django 5.2 on 2025-04-11 19:57

import base.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='warranty_policy',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='id',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='price_bs',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='price_usd',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ar_url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='model_3d_url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='warranty_info',
        ),
        migrations.RemoveField(
            model_name='warranty',
            name='brand',
        ),
        migrations.AddField(
            model_name='product',
            name='price_bs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='inventory', serialize=False, to='products.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.FileField(blank=True, null=True, storage=base.storage.PublicMediaStorage(custom_path='products/images'), upload_to=''),
        ),
    ]
