# Generated by Django 5.2 on 2025-04-16 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warranty',
            old_name='details',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='warranty',
            name='product',
        ),
        migrations.RemoveField(
            model_name='warranty',
            name='warranty_type',
        ),
        migrations.AddField(
            model_name='product',
            name='warranty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.warranty'),
        ),
        migrations.AddField(
            model_name='warranty',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='warranty',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='warranties', to='products.brand'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warranty',
            name='duration_months',
            field=models.PositiveIntegerField(default=12),
        ),
        migrations.AddField(
            model_name='warranty',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
