# Generated by Django 5.2 on 2025-06-21 20:15

import base.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_details_warranty_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ar_url',
            field=models.FileField(blank=True, null=True, storage=base.storage.PublicMediaStorage(custom_path='products/ar_models'), upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='model_3d_format',
            field=models.CharField(blank=True, help_text='Format of 3D model (e.g., glb, gltf, obj)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='model_3d_url',
            field=models.FileField(blank=True, null=True, storage=base.storage.PublicMediaStorage(custom_path='products/3d_models'), upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='supports_ar',
            field=models.BooleanField(default=False, help_text='Whether this product has AR support'),
        ),
    ]
