from app.authentication.serializers.user_serializer import UserSerializer, ChangePasswordSerializer
from app.authentication.serializers.token_serializer import CustomTokenObtainPairSerializer
from app.authentication.serializers.customer_loyalty_serializer import CustomerLoyaltySerializer