# Generated by Django 5.2 on 2025-04-26 02:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_discount_applied_order_discount_percentage'),
        ('parameter', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='delivery_address',
            new_name='address_line1',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='id',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='tracking_info',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='delivery',
            name='actual_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='address_line2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='parameter.city'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delivery',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='parameter.country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delivery',
            name='delivery_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='recipient_name',
            field=models.CharField(default='Home', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delivery',
            name='recipient_phone',
            field=models.CharField(default='+591 12345678', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delivery',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='parameter.state'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivery_status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('shipped', 'Enviado'), ('out_for_delivery', 'En reparto'), ('delivered', 'Entregado'), ('failed', 'Fallido'), ('returned', 'Devuelto')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='estimated_arrival',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='delivery', serialize=False, to='orders.order'),
        ),
        migrations.CreateModel(
            name='DeliveryAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_name', models.CharField(max_length=100)),
                ('recipient_name', models.CharField(max_length=100)),
                ('recipient_phone', models.CharField(max_length=30)),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_addresses', to='parameter.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_addresses', to='parameter.country')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_addresses', to='parameter.state')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', 'address_name'],
            },
        ),
    ]
