# Generated by Django 5.2 on 2025-04-18 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='format',
            field=models.CharField(choices=[('json', 'JSON'), ('pdf', 'PDF'), ('excel', 'Excel')], default='json', max_length=10),
        ),
        migrations.AddField(
            model_name='report',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Español')], default='en', max_length=2),
        ),
        migrations.AddField(
            model_name='report',
            name='report_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('sales_by_customer', 'Sales by Customer'), ('best_sellers', 'Best Sellers'), ('sales_by_period', 'Sales by Period'), ('product_performance', 'Product Performance'), ('inventory_status', 'Inventory Status')], max_length=50),
        ),
    ]
