# Generated by Django 5.2 on 2025-04-18 02:15

import base.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_report_format_report_language_report_report_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='file_path',
            field=models.FileField(blank=True, null=True, storage=base.storage.PublicMediaStorage(custom_path='reports'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='report',
            name='format',
            field=models.CharField(choices=[('json', 'JSON'), ('pdf', 'PDF'), ('excel', 'Excel')], default='json', max_length=20),
        ),
    ]
