# Generated by Django 5.2 on 2025-05-17 15:44

import app.reports.models
import base.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_report_file_path_alter_report_format'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='report',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='report',
            name='start_date',
        ),
        migrations.AddField(
            model_name='report',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='parameters',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='file_path',
            field=models.FileField(blank=True, null=True, storage=base.storage.PublicMediaStorage(), upload_to=app.reports.models.report_file_path),
        ),
        migrations.AlterField(
            model_name='report',
            name='format',
            field=models.CharField(choices=[('json', 'JSON'), ('pdf', 'PDF'), ('excel', 'Excel'), ('html', 'HTML')], default='json', max_length=20),
        ),
        migrations.AlterField(
            model_name='report',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish')], default='en', max_length=10),
        ),
        migrations.AlterField(
            model_name='report',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('sales_by_customer', 'Sales by Customer'), ('best_sellers', 'Best Sellers'), ('sales_by_period', 'Sales by Period'), ('product_performance', 'Product Performance'), ('inventory_status', 'Inventory Status'), ('my_orders', 'My Orders'), ('order_receipt', 'Order Receipt')], max_length=50),
        ),
        migrations.AlterField(
            model_name='report',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
